### ISSUE TITLE
Prepare for 1.4.0

### ISSUE THREAD

**Issue by dhoomakethu** [riptideio/pymodbus#209]
Following issues would be covered and will be updated on need basis
This would cover as an Epic to cover all open tasks pending with PyModbus. Please do not close this issue . All new Issues to be mentioned/referenced here.

- [x] Fix examples #190 
- [x] ~~Fix #160~~  --> Will be handled with 2.0.0. release
- [x] Fix #139
- [x] Fix #135 
- [x] Check #108 
- [x] Fix #107 
- [x] Fix #94 
- [x] ~~Fix #98 ~~ --> Will be handled with 2.0.0. release
- [x] Check #114 
- [x] ~~Check #93~~  --> Will be handled with 2.0.0. release
- [x] Check #84 
- [x] Check #60 
- [x] Check #237
- [x] ~~Check #138~~   --> Will be handled with 2.0.0. release

- [x] Check and Merge PR #227 
- [x] Check and Merge PR #226
- [x] Check and Merge PR #224 
- [x] Check and Merge PR #223
- [x] Check and Merge PR #203
- [x] ~~Check and Merge PR #188~~   --> Will be handled with 2.0.0. release 
- [x] Check and Merge PR #187

**Comment by tryer3000** [comment]
I'd like to know when will 1.4.0 be released.

**Comment by dhoomakethu** [comment]
@tryer3000  No definite timeline is available as of now.

**Comment by dhoomakethu** [comment]
There is a new version available on PyPI just in case somebody wants to give a try
`pip install pymodbus==1.4.0rc2`
