### ISSUE TITLE
Prepare for 2.0.0

### ISSUE THREAD

**Issue by dhoomakethu** [riptideio/pymodbus#254]
Following issues would be covered and will be updated on need basis
This would cover as an Epic to cover all open tasks pending with PyModbus for 2.0.0 release. Please do not close this issue . All new Issues to be mentioned/referenced here.

- [x] Check #37
- [x] Check #47 
~~- [ ] Check #93~~ --> Moved to next release
- [x] Check #138
- [x] Fix #160 
- [x] Fix #212 
- [ ] Fix #220 
- [x] Fix #221 
~~- [ ] Fix #232~~ --> Moved to next release
- [x] Fix #250 

~~- [ ] Check and Merge PR #158~~ --> Moved to next release
- [x] Check and Merge PR #188
- [x] Check and Merge PR #246 
~~- [ ] Check and Merge PR #321~~  --> Moved to next release
- [x] Check and Merge PR #323 

- [x] Add Deprecating warning for old type class instantiation for async clients
